name: Development deployment

on:
  push:
    branches: ["development"]

jobs:
  checkout:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

  test:
    needs: [checkout]
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Decode .env file
        run: echo ${{ secrets.ENV_TEST_FILE }} | base64 -d > .env
      - name: Install latest Yarn
        run: npm i -g yarn
      - name: Run migrations
        run: yarn db:migrate
      - name: Install dependencies
        run: yarn
      - name: Tests e2e
        run: yarn test:e2e

  deploy:
    runs-on: self-hosted
    needs: [test]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Decode .env file
        run: echo ${{ secrets.DEVELOPMENT_ENV_FILE }} | base64 -d > .env
      - name: Install latest Yarn
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn
      - name: Run migrations
        run: yarn db:migrate
      - name: Build
        run: yarn build
      - name: Run server
        run: |
          if pm2 describe main > /dev/null; then
            pm2 restart main --update-env
          else
            pm2 start dist/main.js --name main
          fi


